### ISSUE TITLE
Screen kind of shakes when im in minemen club

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [makamys/Neodymium#38] opened 2023-12-01 00:54 UTC
when I'm playing on mine men club my screen kind of shakes to the point where its annoying when I use the mod. It also happens when I am only using neodymium so I do not think its a conflict with the other mods that I usually use

Without neodymium: https://streamable.com/861dr6

With neodymium: https://streamable.com/rdwpj9

**Comment by makamys** [comment] 2023-12-02 13:53
Looks like a duplicate of https://github.com/makamys/Neodymium/issues/6 if this happens at large coordinates.

**Closed** 2023-12-03 04:00 UTC
